### ISSUE TITLE
Error when pressing "study now" on a deck

### ISSUE THREAD

**Issue by BlenderUser** [iamjustkoi/LeechToolkit#10]
Running with latest update from the addon page. Error code:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-12 18:24:41

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 595, in _onBridgeCmd
  File "aqt\overview.py", line 91, in _linkHandler
  File "aqt\main.py", line 672, in moveToState
  File "aqt\main.py", line 694, in _reviewState
  File "aqt\reviewer.py", line 141, in show
  File "aqt\reviewer.py", line 161, in refresh_if_needed
  File "aqt\reviewer.py", line 209, in nextCard
  File "aqt\reviewer.py", line 284, in _initWeb
  File "aqt\webview.py", line 472, in stdHtml
  File "aqt\hooks_gen.py", line 4099, in __call__
  File "C:\Users\mertt\AppData\Roaming\Anki2\addons21\368380974\src\reviewer.py", line 66, in try_append_wrapper
    reviewer.toolkit_wrapper = ReviewWrapper(reviewer, content, _try_get_current_did())
  File "C:\Users\mertt\AppData\Roaming\Anki2\addons21\368380974\src\reviewer.py", line 112, in __init__
    self.load_options(did)
  File "C:\Users\mertt\AppData\Roaming\Anki2\addons21\368380974\src\reviewer.py", line 148, in load_options
    self.append_marker_html()
  File "C:\Users\mertt\AppData\Roaming\Anki2\addons21\368380974\src\reviewer.py", line 182, in append_marker_html
    self.content.body += self.marker_html()
  File "C:\Users\mertt\AppData\Roaming\Anki2\addons21\368380974\src\reviewer.py", line 171, in marker_html
    .replace('marker_color', self.toolkit_config[Config.LEECH_COLOR]) \
KeyError: 'leechColor'

**Comment by iamjustkoi** [comment]
Fixed and scheduled for release (should happen in a bit)!
Thanks for the report!
