### ISSUE TITLE
Error Message when trying to Update the Collection

### ISSUE THREAD

**Issue by iamjustkoi** [iamjustkoi/LeechToolkit#11]
**Bug/Issue Description**
Issue with using the "Update Collection" button in options to sync the deck.

**To Reproduce**

1. Go to Options then Advanced
2. Click on "Update Collection"

**Error Message**
```
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-16 15:33:52
Add-ons possibly involved: ⁨Leech Toolkit⁩

Caught exception:
Traceback (most recent call last):
File "aqt.taskman", line 122, in _on_closures_pending
File "aqt.taskman", line 71, in <lambda>
File "aqt.taskman", line 90, in wrapped_done
File "aqt.sync", line 112, in on_future_done
File "aqt.main", line 990, in on_collection_sync_finished
File "_aqt.hooks", line 4595, in __call__
File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/sync.py", line 83, in sync_collection
thresholds[key] = deck_conf['lapse']['leechFails']
KeyError: 'lapse'
```

**Additional Context**
Originally reported on AnkiWeb.

**Comment by iamjustkoi** [comment]
Should be fixed and/or caught in the latest release!
