### ISSUE TITLE
Anki 2.1.57 (6b7d372c) Error

### ISSUE THREAD

**Issue by Kosezu** [iamjustkoi/LeechToolkit#15]
Happens after opening Anki 57

Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.2-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-16 15:33:52
Add-ons possibly involved: ⁨Leech Toolkit⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.sync", line 117, in on_future_done
  File "aqt.main", line 1023, in on_collection_sync_finished
  File "_aqt.hooks", line 4624, in __call__
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/sync.py", line 80, in sync_collection
    toolkit_configs: dict = manager.get_all_configs()
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 76, in get_all_configs
    toolkit_configs[f'{deck_name_id.id}'] = merge_fields(self.config.get(str(config_id), {}), self.config)
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 28, in merge_fields
    config[field] = merge_fields(config[field], default_copy[field])
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 28, in merge_fields
    config[field] = merge_fields(config[field], default_copy[field])
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 28, in merge_fields
    config[field] = merge_fields(config[field], default_copy[field])
  [Previous line repeated 983 more times]
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 21, in merge_fields
    default_copy = default_config.copy()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by iamjustkoi** [comment]
Sorry this's popped up for you and thanks, again, for the report!
Will try and look into it and see if it's something I can fix, as soon as I can.
